[package]
name = "vespucci"
description = "Headless GTA V map viewer/editor for Linux"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vespucci"
path = "src/main.rs"

[dependencies]
vespucci-d3d11 = { path = "../vespucci-d3d11" }
vespucci-game = { path = "../vespucci-game" }
vespucci-fxc = { path = "../vespucci-fxc" }
vespucci-world = { path = "../vespucci-world" }
vespucci-render = { path = "../vespucci-render" }
rage-formats = "0.4"
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
png = "0.17"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
